---
# Main playbook for LXD NGINX-proxy container deployment
# This playbook automates the installation and configuration of an LXD container
# running NGINX-proxy for Kubernetes API aggregation and ingress

- name: Deploy LXD NGINX-proxy container
  hosts: localhost
  gather_facts: true
  become: true
  
  vars_files:
    - ./roles/lxd_nginx_proxy/vars/main.yaml
  
  roles:
    - role: lxd_nginx_proxy
...